### ISSUE TITLE
Description field

### ISSUE THREAD

**Issue by andre2007** [thebutterflyprotocol/butterflyd#1]
Please change the value of the description field as it is shown on code.dlang.org:

https://github.com/thebutterflyprotocol/butterflyd/blob/b68f985d30aa7c24aa5fb43ab6f65ed98b341d5a/dub.json#L9

**Comment by deavmi** [comment]
On Wed, 2020-06-17 at 10:15 -0700, andre2007 wrote:
> Please change the value of the description field as it is shown on
> code.dlang.org:
> 
> https://github.com/thebutterflyprotocol/butterflyd/blob/b68f985d30aa7c24aa5fb43ab6f65ed98b341d5a/dub.json#L9
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Will get to it this weekend.

**Comment by deavmi** [comment]
Thanks btw.
